// controllers/pdfController.js
const PDFDocument = require("pdfkit");
const Task = require("../models/Task");
const Project = require("../models/Project"); // <-- optional: agar project model alag hai
const fs = require("fs");
const path = require("path");

// ✅ Helper: format date
const formatDate = (d) => (d ? new Date(d).toLocaleString("en-IN") : "-");

// ✅ Generate PDF for Task or Project
exports.generatePDF = async (req, res) => {
  try {
    const { type, id } = req.params; // type = task | project
    let docData;

    if (type === "task") {
      docData = await Task.findById(id)
        .populate("assignedUsers", "name email role")
        .populate("createdBy", "name email role")
        .populate("remarks.user", "name role email")
        .lean();
    } else if (type === "project") {
      docData = await Project.findById(id)
        .populate("users", "name email role")
        .populate("tasks")
        .lean();
    } else {
      return res.status(400).json({ error: "Invalid PDF type" });
    }

    if (!docData) {
      return res.status(404).json({ error: "Record not found" });
    }

    // 🔹 Create PDF
    const doc = new PDFDocument({ margin: 40 });
    const fileName = `${type}-${id}.pdf`;
    const filePath = path.join(__dirname, "../../uploads/pdfs", fileName);
    const pdfStream = fs.createWriteStream(filePath);
    doc.pipe(pdfStream);

    // --- Header ---
    doc
      .fontSize(22)
      .fillColor("#1a73e8")
      .text(type === "task" ? "Task Report" : "Project Report", { align: "center" })
      .moveDown(0.5);
    doc
      .fontSize(10)
      .fillColor("gray")
      .text(`Generated: ${new Date().toLocaleString("en-IN")}`, { align: "right" })
      .moveDown(1);

    // --- Basic Info ---
    doc.fontSize(12).fillColor("black").text("📋 Basic Information", { underline: true }).moveDown(0.5);

    if (type === "task") {
      doc.text(`Title: ${docData.title}`);
      doc.text(`Description: ${docData.description || "-"}`);
      doc.text(`Priority: ${docData.priority}`);
      doc.text(`Priority Days: ${docData.priorityDays}`);
      doc.text(`Due Date: ${formatDate(docData.dueDateTime)}`);
      doc.text(`Created By: ${docData.createdBy?.name || "-"} (${docData.createdBy?.role || "-"})`);
      doc.text(`WhatsApp: ${docData.whatsappNumber || "-"}`);
    } else {
      doc.text(`Title: ${docData.projectName}`);
      doc.text(`Description: ${docData.description || "-"}`);
      doc.text(`Start Date: ${formatDate(docData.startDate)}`);
      doc.text(`End Date: ${formatDate(docData.endDate)}`);
      doc.text(`Status: ${docData.status || "-"}`);
    }

    doc.moveDown(1);

    // --- Assigned Users ---
    doc.fontSize(12).fillColor("black").text("👥 Assigned Users", { underline: true }).moveDown(0.5);
    const users = type === "task" ? docData.assignedUsers : docData.users;
    if (users?.length) {
      users.forEach((u, i) => doc.text(`${i + 1}. ${u.name} (${u.role}) - ${u.email}`));
    } else doc.text("No assigned users.");

    doc.moveDown(1);

    // --- Remarks ---
    doc.fontSize(12).fillColor("black").text("💬 Remarks", { underline: true }).moveDown(0.5);
    if (docData.remarks?.length) {
      docData.remarks.forEach((r, i) => {
        doc.font("Helvetica-Bold").text(`${i + 1}. ${r.user?.name || "Unknown"}`, { continued: true });
        doc.font("Helvetica").text(` (${formatDate(r.createdAt)}):`);
        doc.text(`${r.text}`).moveDown(0.5);
      });
    } else doc.text("No remarks yet.");

    doc.moveDown(1);

    // --- Attachments ---
    doc.fontSize(12).fillColor("black").text("📎 Attachments", { underline: true }).moveDown(0.5);
    if (docData.files?.length) {
      docData.files.forEach((f, i) => doc.text(`${i + 1}. ${f.originalName} (${f.filename})`));
    } else doc.text("No file attachments.");

    if (docData.voiceNote) {
      doc.moveDown(0.5);
      doc.text(`🎤 Voice Note: ${docData.voiceNote.originalName}`);
    }

    doc.moveDown(1);

    // --- Status History ---
    if (docData.statusHistory?.length) {
      doc.fontSize(12).fillColor("black").text("📜 Status History", { underline: true }).moveDown(0.5);
      docData.statusHistory.forEach((h, i) => {
        doc.text(`${i + 1}. ${h.status.toUpperCase()} by ${h.changedBy || "Unknown"} on ${formatDate(h.changedAt)}`);
        if (h.remarks) doc.text(`   Remarks: ${h.remarks}`).moveDown(0.2);
      });
    }

    // --- Footer ---
    doc.moveDown(1);
    doc
      .fontSize(10)
      .fillColor("gray")
      .text("Generated by CIIS Task Management System", { align: "center" });

    doc.end();

    pdfStream.on("finish", () => {
      res.download(filePath, fileName, (err) => {
        if (err) console.error("PDF download error:", err);
        setTimeout(() => fs.unlink(filePath, () => {}), 5000);
      });
    });
  } catch (err) {
    console.error("❌ PDF generation failed:", err);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
};
